# Generated by Django 2.1.1 on 2018-11-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='unitWeight',
            new_name='shipping_weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
    ]
