# Generated by Django 2.1.1 on 2018-11-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspsite', '0003_auto_20181130_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='group',
            new_name='category',
        ),
    ]
