# Generated by Django 2.1.1 on 2018-11-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspsite', '0004_auto_20181130_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='group',
            field=models.CharField(default='default_group', max_length=30),
            preserve_default=False,
        ),
    ]
