# Generated by Django 2.1.1 on 2018-11-30 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspsite', '0005_location_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forget_password',
            name='user',
        ),
        migrations.DeleteModel(
            name='Forget_password',
        ),
    ]
