# Generated by Django 2.1.1 on 2018-12-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspsite', '0009_auto_20181201_0130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pack',
            new_name='Drone',
        ),
    ]
