# Generated by Django 2.1.1 on 2018-12-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspsite', '0010_auto_20181201_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drone',
            new_name='Pack',
        ),
    ]
