# Generated by Django 2.1.1 on 2018-12-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspsite', '0011_auto_20181201_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='order',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
    ]
