# Generated by Django 2.1.1 on 2018-12-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspsite', '0013_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_lable',
            name='order',
        ),
        migrations.DeleteModel(
            name='Shipping_Lable',
        ),
    ]
