# Generated by Django 2.1.1 on 2018-12-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aspsite', '0014_auto_20181201_1344'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pack',
            new_name='Drone',
        ),
    ]
