# Generated by Django 2.1.1 on 2018-12-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspsite', '0017_auto_20181201_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=10),
        ),
    ]
