# Generated by Django 2.1.3 on 2018-11-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('name', models.CharField(help_text='Enter the clinic name with max length 200', max_length=200, primary_key=True, serialize=False)),
                ('lat', models.IntegerField(help_text='latitude for clinic')),
                ('long', models.IntegerField(help_text='longitude for clinic')),
                ('alt', models.IntegerField(help_text='altitude for clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField(editable=False)),
                ('status', models.CharField(blank=True, choices=[('qp', 'Queued for Processing'), ('pw', 'Processing by WareHouse'), ('qd', 'Queued for Dispatching'), ('di', 'Dispatched'), ('de', 'Delivered')], default='dq', help_text='Order status', max_length=1)),
                ('orderedtime', models.DateTimeField(blank=True, null=True)),
                ('dispatchedtime', models.DateTimeField(blank=True, null=True)),
                ('arrivedtime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSupplyMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofsupply', models.IntegerField(help_text='Number of supply needed')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a supply name with max length 200', max_length=200)),
                ('weight', models.IntegerField(help_text='Enter the wight of supply')),
                ('image', models.ImageField(help_text='Upload a image of supply', upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='ordersupplymatching',
            name='supply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Supply'),
        ),
    ]
