# Generated by Django 2.1.3 on 2018-11-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181106_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='alt',
            field=models.FloatField(help_text='altitude for clinic'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='lat',
            field=models.FloatField(help_text='latitude for clinic'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='long',
            field=models.FloatField(help_text='longitude for clinic'),
        ),
    ]
