# Generated by Django 2.1.3 on 2018-11-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181106_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='weight',
            field=models.FloatField(help_text='Enter the weight of supply'),
        ),
    ]
