# Generated by Django 2.1.3 on 2018-11-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20181106_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Clinic'),
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.IntegerField(default=0, help_text='Enter priority in integer with max priority 9 to min priority 0.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('qp', 'Queued for Processing'), ('pw', 'Processing by WareHouse'), ('qd', 'Queued for Dispatching'), ('di', 'Dispatched'), ('de', 'Delivered')], default='dq', help_text='Order status', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
