# Generated by Django 2.1.3 on 2018-11-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20181106_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='clinic',
            new_name='destination',
        ),
    ]
