# Generated by Django 2.1.3 on 2018-11-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20181106_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersupplymatching',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordersupplymatching',
            name='supply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Supply'),
            preserve_default=False,
        ),
    ]
