# Generated by Django 2.1.3 on 2018-11-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20181106_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['priority', 'order_id']},
        ),
    ]
