# Generated by Django 2.1.3 on 2018-11-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20181106_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.IntegerField(help_text='Enter priority in integer with most priority 1 to least priority 9.'),
        ),
    ]
