# Generated by Django 2.1.3 on 2018-11-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20181106_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
