# Generated by Django 2.1.3 on 2018-11-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20181106_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxweight', models.FloatField(help_text='Enter the max weight of drone')),
                ('csvfile', models.FileField(editable=False, upload_to='')),
                ('order', models.ManyToManyField(help_text='Select order for this drone', to='catalog.Order')),
            ],
        ),
    ]
