# Generated by Django 2.1.3 on 2018-11-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_drone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceBetween2Clinics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(help_text='distance in km')),
                ('clinicA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicA', to='catalog.Clinic')),
                ('clinicB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicB', to='catalog.Clinic')),
            ],
        ),
    ]
