# Generated by Django 2.1.3 on 2018-11-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20181106_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='csvfile',
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], help_text='Enter priority in integer with most priority 1 to least priority 9.', max_length=1),
        ),
    ]
