# Generated by Django 2.1.3 on 2018-11-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20181114_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersupplymatching',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='catalog.Order'),
        ),
    ]
